approvedGitRepositories:
  - "**"

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.17.1.cjs
