name: JavaScript Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/VSCodeExtension/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            .yarn/cache
            **/node_modules
            **/.eslintcache
            **/yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}

      - name: Yarn install
        working-directory: ./Source/VSCodeExtension
        run: yarn

      - name: Build and verify
        working-directory: ./Source/VSCodeExtension
        run: yarn ci
